Exception in thread "main" java.lang.AssertionError: Error while testing (Constant 10.0): No error expected in (toStringSuffix (Constant 10.0))
at jstest.expression.BaseTester.test(Unknown Source)
at jstest.expression.Builder.lambda$selector$4(Unknown Source)
at base.Selector$Composite.lambda$v$0(Unknown Source)
at base.Selector.lambda$test$2(Unknown Source)
at base.Log.lambda$action$0(Unknown Source)
at base.Log.silentScope(Unknown Source)
at base.Log.scope(Unknown Source)
at base.Log.scope(Unknown Source)
at base.Selector.lambda$test$3(Unknown Source)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at base.Selector.test(Unknown Source)
at base.Selector.main(Unknown Source)
at cljtest.parsing.FullParserTest.main(Unknown Source)
Caused by: jstest.EngineException: No error expected in (toStringSuffix (Constant 10.0))
at cljtest.ClojureScript.call(Unknown Source)
at cljtest.ClojureScript$F.call(Unknown Source)
at cljtest.ClojureEngine.toString(Unknown Source)
at cljtest.object.ObjectTester.lambda$test$3(Unknown Source)
at base.TestCounter.lambda$test$0(Unknown Source)
at base.TestCounter.lambda$testV$2(Unknown Source)
at base.Log.silentScope(Unknown Source)
at base.TestCounter.testV(Unknown Source)
at base.TestCounter.test(Unknown Source)
at cljtest.object.ObjectTester.test(Unknown Source)
at jstest.expression.BaseTester.lambda$test$1(Unknown Source)
at base.Log.lambda$action$0(Unknown Source)
at base.Log.silentScope(Unknown Source)
at base.Log.scope(Unknown Source)
at base.Log.scope(Unknown Source)
at jstest.expression.BaseTester.test(Unknown Source)
... 13 more
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'user/toStringSuffix
at clojure.lang.Var$Unbound.throwArity(Var.java:45)
at clojure.lang.AFn.invoke(AFn.java:32)
at clojure.lang.Var.invoke(Var.java:384)
at cljtest.ClojureScript.callUnsafe(Unknown Source)
... 29 more
ERROR: Tests: failed
